const { exit } = require('process');

fs = require('fs');

function touchDir(dir) {
	if (!fs.existsSync(dir)){
		fs.mkdirSync(dir);
		return true
	} else {
		return false
	}
}


// increase array element. Maximum is the maximum of one element. Element overflow, if everything is max, false returned
function increaseArray(array, max) {
	for (let index = array.length -1; index >= 0; index--) {
		if (array[index] < max) {
			array[index] += 1
			return array
		} else {
			array[index] = 0
		}
	}
	return false
}


// return a dict filled with example data
function generateExampleDict(maxStrLen) {
	let input = [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
				  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
				  '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'
	 ]
	// let input = [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o' ]
	
	var data = []
	for (let i = 1; i <= maxStrLen; i++) {
		console.log('generating', i, 'length')
		//generate number array
		var startArray = []
		for (let j = 0; j < i; j++) {
			startArray.push(0)
		}


		while (startArray) {
			if (i >= 5 && startArray[startArray.length - 1] == 0 && startArray[startArray.length - 2] == 0 && startArray[startArray.length - 3] == 0) {
				console.log(startArray)
			}
			string = ''
			for (let k = 0; k < startArray.length; k++) {
				string += input[startArray[k]]
				
			}
			data.push([string, "This_is_an_example_value_for_key_" + string])
			startArray = increaseArray(startArray, input.length-1)
		}
	}
	return data
}

const noop = () => {};




var dir = __dirname + '/../dist';
if (touchDir(dir) == false) {
	console.log("The /dist folder already exist, please delete it.")
	process.exit(1)
}

touchDir(dir + '/data')

fs.copyFile( __dirname + '/../viewer/example.html', dir + '/index.html', (err) => {
	if (err) throw err;
	console.log('example.html was copied to index.html');
});

fs.copyFile(__dirname + '/../viewer/lookup.js', dir + '/lookup.js', (err) => {
	if (err) throw err;
	console.log('source.txt was copied to destination.txt');
});


console.log('Generation example data')
var data = generateExampleDict(4)


console.log('Sorting', data.length, 'rows')
data.sort(function(x, y) {
	if (x[0] < y[0]) {
	  return -1;
	}
	if (x[0] > y[0]) {
	  return 1;
	}
	return 0;
});

console.log('writing', parseInt(data.length/1000), 'files')
var indexFileContent = 'index # example data generated by SkyLookup\n'
var linesInFile = 0
var contentToWrite = 'final #\n'
var nextFileName = 0
var firstLineInFile = ''

for (let i = 0; i < data.length; i++) {
	if (linesInFile < 1000) {
		contentToWrite += data[i][0] + ' ' + data[i][1] + '\n'
		if (linesInFile == 0) {
			firstLineInFile = data[i][0]
		}
		linesInFile += 1
	} else {
		fs.writeFileSync(dir + '/data/' + nextFileName + '.txt', contentToWrite, noop)
		linesInFile = 0
		contentToWrite = 'final #\n'
		indexFileContent += firstLineInFile + ' data/' + nextFileName + '.txt\n'
		firstLineInFile = ''
		nextFileName += 1
	}
}
// WRITE indexFileContent
console.log('writing index file')
fs.writeFileSync(dir + '/data/index.txt', indexFileContent, noop)




// fs.writeFile('', data, [encoding], [callback])